# Generated by Django 2.0.2 on 2018-02-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bootstrap_table_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adddate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=1),
        ),
    ]
